sudo: required
services:
  - docker 

before_install:
  - docker build -t lfbds/docker-react -f dockerfile.dev .

script: 
  -  docker run -e CI=true lfbds/docker-react  npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-739292332581"
  bucket_path: "docker-react"
  on:
    branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key:
       secure: "$AWS_SECRET_KEY"
     
